### PR TITLE
feat(embed): allow custom links in the actions menu

### LINKED ISSUE #156: Enable custom "actions" in dropdown menu
I would like to add my own links or javascript actions in the actions menu. Based off `embed.ts#L21` I believe these actions are hard coded. Is this something we are open too? Does anyone have an opinion on implementation?

https://github.com/vega/vega-embed/blob/1ea996fa8ebf56433cd2a2c09ba275c3b055d865/src/embed.ts#L21

### PR DESCRIPTION
**Pull request by SyntaxRules**
Closes #156

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you for the PR. I want to think about this a bit more before merging it. I suspect that one might want to have a bit more power and create links that depend on the spec or the view. However, then we would need to support functions in the embed options and I would like to avoid that (because functions cannot be serialized or generated from Python).

@SyntaxRules Would you be okay with using your own version of embed for now until we decide whether we merge this feature?

**Comment by SyntaxRules** [comment]
I can be patient. I'm going to be using this to redirect to other pages that show different versions of this same spec.

Its worth pointing out that javascript functions can be ran inside of href tags. So in theory a configuration like this would work to run a custom javascript action on click:
```
actions: {
      customOptions: { 'Javascript Alert': 'javascript:MyFunction();'}
    }
```
See https://stackoverflow.com/a/11348403/1767377

Its up to you to decide is this kind of HTML hackery is sufficient. With it you could edit the spec and reload it on click.

**Comment by SyntaxRules** [comment]
@domoritz Any updates on this? I'm happy to refactor if necessary.

**Comment by domoritz** [comment]
I'm still not happy with this as it targets a very specific use case but is not flexible enough to support others. For example, if I wanted to implement my own "Show Source" or "Open in Editor", I wouldn't be able to do that. Moreover, supporting arbitrary Javascript is a security risk that I don't want to add. We have taken great care to not allow arbitrarily JavaScript in Vega and Vega-Lite and supporting arbitrary JavaScript in embed would negate the benefits.

**Comment by domoritz** [comment]
I think this functionality can be achieved without modifying Vega-Embed. You can add any dom elements to the actions menu from outside embed. I'm not convinced that there is enough need to support this via the JSON api.

**Pull request closed without merging**
