### PR TITLE
Expose vega & vl, allow spec overwrites, migrate to ES6

### PR DESCRIPTION
**Pull request by nyurik**

### CODE REVIEW

**Comment by domoritz** [comment]
Fantastic!

One issue is that we try to also output es5 code so we need a compile step. At this point, I wonder whetehr we should jsut switch to typescript. Typescript is very similar to ES6 so we can start from what you've done in this pr.

**Comment by domoritz** [comment]
@nyurik: I started at https://github.com/vega/vega-embed/tree/dom/typescript. Can you take over from there? I definitely want to merge your changes but we need to stay ES5 compatible.

**Comment by domoritz** [comment]
Okay, how about we just switch `const -> var` and then we are ES5 compatible again.

**Comment by domoritz** [comment]
cc @yhoonkim

**Comment by yhoonkim** [comment]
@nyurik , I accidently push a commit that adds some blank lines and changes version of Vega on your repo to merge this. Hope it's ok but if you get any trouble, I'll help you to fix it.

**Pull request merged**
