### PR TITLE
feat: add vega interpreter as dependency and support custom interpreter

### PR DESCRIPTION
**Pull request by domoritz**
Needs https://github.com/vega/vega/pull/2712

### CODE REVIEW

**Comment by domoritz** [comment]
Alternatively, I could try to load the expression parser from `vega` (unless otherwise specified) and expect users who bundle their app to always provide the expression parser directly.

However, it looks like the parser is pretty small and it is nice that we don't require users to do any extra work to use the expression parser.

**Comment by domoritz** [comment]
Someone should redo this pull request.

**Comment by domoritz** [comment]
Will redo if anyone requests this feature.

**Comment by stefanw** [comment]
Hey @domoritz, I would appreciate this feature. Right now, passing `ast: true` does not help much without a custom vega build because [`vega.expressionInterpreter` needs to exist](https://github.com/vega/vega-embed/blob/641b65e1bcbaaf2a2b70c783fc0fe1bdfb825d6e/src/embed.ts#L357) which it does not when using ES module bundling. I'm currently working around it like this to make sure `expr` on the vega view is set:

```
import * as vega from 'vega';
import { expressionInterpreter } from 'vega-interpreter';
import embed from 'vega-embed';

class CSPVegaView extends vega.View {
  constructor (runtime, opt) {
    opt.expr = expressionInterpreter
    super(runtime, opt);
  }
}

// ... define el, spec
embed(el, spec, {
    viewClass: CSPVegaView,
    ast: true
  })
```

It's a bit cumbersome. I think either shipping `vega-embed` with `vega-interpreter` as a dependency or allowing to pass in your own `expr` option to embed could be a solution.

---
Also: congratulations on your recent career step! Awesome that you still find the time to work on vega stuff.

**Comment by domoritz** [comment]
Oh hello. Nice to see you here. I'll put it back in my queue to finish this up.

**Comment by domoritz** [comment]
I put it in my heap instead.

**Pull request closed without merging**
